Feat/add shadcn
annaleeee/Next-to-do-list pull request #13
Opened 2024-02-13 06:52 UTC by annaleeee

2024-02-14 02:45 UTC, NEARworld requested changes

2024-02-14 02:45 UTC, NEARworld commented on components/NewProjectDialog.tsx
> +  })
`Dialog` 를 통해 제출해야하는 값들이 적혀있어야 되겠네요

2024-02-14 02:45 UTC, NEARworld commented on components/NewProjectDialog.tsx
> +        },
`defaultValues`의 프로퍼티도 `Dialog`에 있는 필드에 맞게 수정해주세요

2024-02-14 02:45 UTC, NEARworld commented on components/NewProjectDialog.tsx
> +        console.log(values);
submit 후에 `values` 변수 안에 달력에서 입력한 날짜 값이 들어있는지 확인해봐야 될 듯합니다.

2024-02-14 02:45 UTC, NEARworld commented on components/NewProjectDialog.tsx
> +        setDate(null);
달력 날짜 값이 `react-hook-form`의 `form`을 통해 저장되는지 확인해봐야할 거 같습니다.

2024-02-14 02:47 UTC, annaleeee commented on components/NewProjectDialog.tsx
> +  })
username 수정 완료했습니다

2024-02-14 02:47 UTC, annaleeee commented on components/NewProjectDialog.tsx
> +        },
수정 완료했습니다

2024-02-15 07:10 UTC, annaleeee commented on components/NewProjectDialog.tsx
> +        console.log(values);
수정 완료했습니다

2024-02-15 07:10 UTC, annaleeee commented on components/NewProjectDialog.tsx
> +        setDate(null);
수정 완료했습니다

2024-02-15 07:11 UTC, NEARworld approved these changes

2024-02-15 07:11 UTC, merged